### ISSUE TITLE
https://holochain.net fails to redirect

### ISSUE THREAD

**Issue by zippy** [holochain/website#17]
but regular http://holochain.net works

**Comment by samcooley** [comment]
Have re-issued the AWS certificate for holochain.org, www.holochain.org, holochain.net, www.holochain.net; once that validates, plan to apply it to cloudfront distribution and then update holochain.net DNS to use that and thereby hopefully resolve the issue with https not working for holochain.net.

**Comment by samcooley** [comment]
@zippy @bboyatwork @Bortseb I believe this is resolved based on my above actions + alignment of CDN usage across domains and DNS/CDN providers; please check, and I think it should also resolve #2, if that was not already.  Hopefully both can be closed now.

**Comment by samcooley** [comment]
For the record, #2 actually seems related to http:// in the favicon link, so can be seen as separate from this issue.
