### ISSUE TITLE
Hackathons: Add pending and scheduled ones

### ISSUE THREAD

**Issue by artbrock** [Holochain/website#24]
Melbourne, Australia -- March 8-10
Copenhagen, Denmark -- March 23-25
Austin TX -- May 25-27

**Comment by zippy** [comment]
I've added the base files in this branch:  https://github.com/Holochain/website/tree/24-hackathons

Please note the template assumes that you have text describing what makes the hackathons different.  I've just copied over the same data that was in the india hackathon. This needs to be fixed.  Also the Map is totally boring until there's actually an address!!

**Comment by inconstantloop** [comment]
Sao Paulo, Brazil - March 30. Meetup https://www.facebook.com/events/200885130508582/

**Comment by inconstantloop** [comment]
Brussels - Belgium: Pending
Boulder, Colorado: Pending.
Geneva, Switzerland: Pending.

**Comment by zippy** [comment]
I don't know who closed this ticket.  It wasn't done.  

@inconstantloop @artbrock could you please provide details for these, so I can add them to the site.
