### ISSUE TITLE
text too small in main page buttons at narrowest size

### ISSUE THREAD

**Issue by zippy** [holochain/website#41]
It looks like there's some kind of weird re-sizing thing where the button text is way too small when you resize the window to the very narrowest setting.

**Comment by celestialhanley** [comment]
Micah and I are going to co-code on this task.

**Comment by celestialhanley** [comment]
@zippy could you review this change? specifically, if we submitted this correctly or if we need to create a new branch. thx!

**Comment by zippy** [comment]
@celestialhanley That works great.  For a small change like this that's so obviously correct, doing it directly on master is fine.  But if it's more complicated, doing a branch is important, because if there's a problem, then it doesn't block progress.  I.e. let's say I'm working on some other feature/fix, that can then be merged to master and deployed while this is still in review and gets fixed.
